blank_issues_enabled: false
contact_links:
  - name: Ideas & General Discussion
    url: https://github.com/LeDevNovice/verso/discussions
    about: For open-ended ideas, questions, or feedback : start a Discussion instead.
